{% set name = "ciocheck" %}
{% set version = "0.1.1" %}
{% set hash_type = "sha256" %}
{% set hash = "03d02a7c5348e2d040e8e229254d447ef51f2076cfb8153d4b25f32ea3915488" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ContinuumIO/{{ name }}/archive/v{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 1

requirements:
  build:
    - python
    - setuptools
  run:
    - autopep8
    - coverage
    - flake8
    - isort
    - pydocstyle
    - pylint
    - pytest
    - pytest-cov
    - pytest-json
    - pytest-xdist
    - python
    - six
    - yapf

test:
  imports:
    - ciocheck

about:
  home: https://github.com/ContinuumIO/ciocheck
  summary: "Continuum Analytics linter/formater/tester helper"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/ContinuumIO/ciocheck

extra:
  recipe-maintainers:
    - goanpeca
