# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "oq0QWEQxVAVW1HZ2eTkonh/MEtYrI837ZhnOPbpp9nXzO8/+42PHxU7R0Esy6pItyLJ+jactvxXiBlZS6RkGAWStNIzkc1EsESyZ9+7HOPA82w1GIkFF2/MSDvg6o13qcEVIybQP+eboE3Ev9EjxFTCCeZXUlrEDC5evmqJAM0fFnlI/T12zczOLm7z4K7lwRD4zJJx/G4UnQZosTu0sesp0WJwT6YUDs0joq48oC6NmMYx6SMjMh33/+5VsDzPqFjkod0oitFL9q++h13s51CiBobuxk2wEZXD/9jLt23Bj6oCDHIG4uy/7xUyOe30T/cvxQFY6UvRamKXqAdGkLB+2+jnqtdz7RMmiv3pZqAydPEccZ0n3PhQUUq6hxFB8d3zyUcSpqU+TD25fhZt2gjmEy0jKE3i+s4qrMzrg39iYJBwBghP8NYgOzsyN9LlByJoz9Zb1PCTjRxwn21t+mh/hMihrwEraD/QG1hFmGrsdZ7GdIHVb3jIlZQ1sbX9xll2HJJCHD80YkzZxfjR9Uqv4bUzEaL86/v0f+vtd/bh+nIZYej6LbSXbPX3YwHQmwqaL8IDyg6zkSQXuGaQwbJAFDXJeCRqABe6WlkwlvifWX9Y+kwzxxrwqAizo3pWIAs+0JzwOW+N430rGvPDbS5fZqPf6crAXyt/IWDaMVHU="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
