travis:
  secure:
    BINSTAR_TOKEN: YCGOLB9jlkRf+Tjl4TOCl7oq5iGQWeI01FZwVBEAo6cwoIbfs2SmWZWJ5njXFIULzBKd57gSZwqwE+bxu5Gjtq/FoMWBSxmuJ3iT3j67Qv+5doouyfJyf2ZfgGjwWxH3brPCVThDa1pZhACOx0jXKA2dcFOFvaGDMSNK4tUd2/fJbFikZzo4srtUSoK4YOOFHbTVDoSP6SrNclbaFX20/mdjUlY3CbOIpOQkd/+IlDZrR0YdKlALOyA06RG20zV/i6W7txrN1QNHOa/5Xo273U3JBSeOGBovm7eTcWfNrLyEKMvFBeiKvkinw3XlAit3krZnsQITZPK8sMTPXmMBe+yzQ0bIEvd/Xg0uOh+ua4dBzojJGJDFw9XljUNjN4wm5TPNzEWbYVQSkb92kAfuj2cJSS+5Od79uGfc4+LhC40MKp6zlt3QGL19gorVqJwZ7vTcvx42Z9vTc4eAVrDtZJKsy2XR8OG6JD9EctV3zmwMf9GowiS1qKmCf/OL3yPx0km8kO4TGKqr/csR6dwyIny/y6h7zS2SW7eUjOjgjIFHK5R7H6ICs8jE3Q34iCeNjGn5KRWzKPeaKYWeE8Bc/wuKZgL+7aKY2VodWkD01Cf9NC7jE4ylkTJ3uC5OQevTn57Xk0sa5KUQgJkEfN7YWAW9ZzLOQNwqcKSpdtR3u1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
