travis:
  secure:
    BINSTAR_TOKEN: oq0QWEQxVAVW1HZ2eTkonh/MEtYrI837ZhnOPbpp9nXzO8/+42PHxU7R0Esy6pItyLJ+jactvxXiBlZS6RkGAWStNIzkc1EsESyZ9+7HOPA82w1GIkFF2/MSDvg6o13qcEVIybQP+eboE3Ev9EjxFTCCeZXUlrEDC5evmqJAM0fFnlI/T12zczOLm7z4K7lwRD4zJJx/G4UnQZosTu0sesp0WJwT6YUDs0joq48oC6NmMYx6SMjMh33/+5VsDzPqFjkod0oitFL9q++h13s51CiBobuxk2wEZXD/9jLt23Bj6oCDHIG4uy/7xUyOe30T/cvxQFY6UvRamKXqAdGkLB+2+jnqtdz7RMmiv3pZqAydPEccZ0n3PhQUUq6hxFB8d3zyUcSpqU+TD25fhZt2gjmEy0jKE3i+s4qrMzrg39iYJBwBghP8NYgOzsyN9LlByJoz9Zb1PCTjRxwn21t+mh/hMihrwEraD/QG1hFmGrsdZ7GdIHVb3jIlZQ1sbX9xll2HJJCHD80YkzZxfjR9Uqv4bUzEaL86/v0f+vtd/bh+nIZYej6LbSXbPX3YwHQmwqaL8IDyg6zkSQXuGaQwbJAFDXJeCRqABe6WlkwlvifWX9Y+kwzxxrwqAizo3pWIAs+0JzwOW+N430rGvPDbS5fZqPf6crAXyt/IWDaMVHU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
